// GENERATED by scripts/generate-editor-protocol.py from dgc/editor_protocol.py.
// Do not edit this file directly.

export const DGC_PROTOCOL_VERSION = 5 as const;
export const MAX_EVENT_BYTES = 4194304;
export const MAX_COMMAND_BYTES = 4194304;
export const MAX_PENDING_BYTES = 4194304;
export const MAX_PENDING_COMMANDS = 256;

export type DgcEventType = "ready" | "turn_start" | "turn_end" | "text_delta" | "thinking_delta" | "stream_end" | "tool_call" | "tool_progress" | "tool_result" | "tool_denied" | "todos" | "artifact_ready" | "goal_changed" | "info" | "error" | "request_expired" | "permission_request" | "rule_added" | "plan_proposal" | "options_request" | "mcp_input_request" | "context" | "compacted" | "artifacts" | "config" | "status" | "model_changed" | "mode_changed" | "think_changed" | "models" | "mcp_tools" | "mcp_call_complete" | "skill_catalog" | "skill_detail" | "docs_catalog" | "doc" | "mcp_servers" | "permissions" | "memory" | "session_named" | "hook_catalog" | "hook_activity" | "handoff_started" | "handoff" | "queued" | "command_rejected" | "workspace_roots" | "saved_plan" | "session" | "history" | "sessions" | "checkpoints" | "rewound" | "retained_tasks";
export type DgcCommandType = "prompt" | "slash_command" | "set_workspace_roots" | "permission_response" | "plan_response" | "options_response" | "mcp_input_response" | "cancel" | "interrupt" | "set_mode" | "set_model" | "list_models" | "list_mcp_tools" | "call_mcp_tool" | "list_skills" | "reload_skills" | "get_skill" | "list_docs" | "get_doc" | "list_mcp_servers" | "upsert_mcp_server" | "remove_mcp_server" | "reload_mcp_servers" | "list_permissions" | "add_permission_rule" | "remove_permission_rule" | "get_memory" | "add_memory" | "list_hooks" | "generate_handoff" | "set_think" | "set_goal" | "get_goal" | "get_plan" | "new_session" | "name_session" | "clear_session" | "resume_session" | "list_sessions" | "delete_session" | "list_checkpoints" | "rewind" | "list_retained_tasks" | "resolve_retained_task" | "compact" | "list_artifacts" | "stop_artifact" | "set_config" | "get_config" | "status" | "shutdown";
export interface DgcEvent { type: DgcEventType; seq: number; [key: string]: any; }
export interface DgcCommand { type: DgcCommandType; [key: string]: any; }

type FieldSpec = { types: string[]; required: boolean; enum?: unknown[] };
const EVENT_FIELDS: Record<string, Record<string, FieldSpec>> = {
  "ready": {
    "version": {
      "types": [
        "string"
      ],
      "required": true
    },
    "protocol_version": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "capabilities": {
      "types": [
        "object"
      ],
      "required": true
    },
    "model": {
      "types": [
        "string"
      ],
      "required": true
    },
    "mode": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "default",
        "acceptEdits",
        "plan",
        "auto"
      ]
    },
    "think": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "off",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "ultra_mode": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "base_url": {
      "types": [
        "string"
      ],
      "required": true
    },
    "subagent_base_url": {
      "types": [
        "string"
      ],
      "required": false
    },
    "fallback_base_url": {
      "types": [
        "string"
      ],
      "required": false
    },
    "project_root": {
      "types": [
        "string"
      ],
      "required": false
    },
    "workspace_trusted": {
      "types": [
        "boolean"
      ],
      "required": true
    },
    "commands": {
      "types": [
        "array"
      ],
      "required": true
    },
    "custom_commands": {
      "types": [
        "array"
      ],
      "required": true
    },
    "session_id": {
      "types": [
        "null",
        "string"
      ],
      "required": false
    },
    "tools_supported": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "provider": {
      "types": [
        "string"
      ],
      "required": false
    },
    "provider_capabilities": {
      "types": [
        "object"
      ],
      "required": false
    },
    "tools": {
      "types": [
        "array"
      ],
      "required": false
    },
    "skills": {
      "types": [
        "array"
      ],
      "required": false
    },
    "goal": {
      "types": [
        "object"
      ],
      "required": true
    },
    "context_size": {
      "types": [
        "integer"
      ],
      "required": true
    }
  },
  "turn_start": {
    "turn_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "prompt": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "turn_end": {
    "turn_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "reason": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "completed",
        "cancelled",
        "error"
      ]
    },
    "token_estimate": {
      "types": [
        "integer"
      ],
      "required": true
    }
  },
  "text_delta": {
    "text": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "thinking_delta": {
    "text": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "stream_end": {},
  "tool_call": {
    "call_id": {
      "types": [
        "null",
        "string"
      ],
      "required": false
    },
    "name": {
      "types": [
        "string"
      ],
      "required": true
    },
    "args": {
      "types": [
        "object"
      ],
      "required": true
    },
    "summary": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "tool_progress": {
    "call_id": {
      "types": [
        "null",
        "string"
      ],
      "required": false
    },
    "name": {
      "types": [
        "string"
      ],
      "required": true
    },
    "message": {
      "types": [
        "string"
      ],
      "required": true
    },
    "progress": {
      "types": [
        "number"
      ],
      "required": false
    },
    "total": {
      "types": [
        "number"
      ],
      "required": false
    },
    "level": {
      "types": [
        "string"
      ],
      "required": false,
      "enum": [
        "debug",
        "info",
        "notice",
        "warning",
        "error",
        "critical",
        "alert",
        "emergency"
      ]
    }
  },
  "tool_result": {
    "call_id": {
      "types": [
        "null",
        "string"
      ],
      "required": false
    },
    "name": {
      "types": [
        "string"
      ],
      "required": true
    },
    "output": {
      "types": [
        "string"
      ],
      "required": true
    },
    "is_error": {
      "types": [
        "boolean"
      ],
      "required": true
    },
    "is_diff": {
      "types": [
        "boolean"
      ],
      "required": true
    },
    "diff": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "tool_denied": {
    "call_id": {
      "types": [
        "null",
        "string"
      ],
      "required": false
    },
    "name": {
      "types": [
        "string"
      ],
      "required": true
    },
    "args": {
      "types": [
        "object"
      ],
      "required": true
    },
    "reason": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "todos": {
    "todos": {
      "types": [
        "array"
      ],
      "required": true
    }
  },
  "artifact_ready": {
    "id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "name": {
      "types": [
        "string"
      ],
      "required": true
    },
    "url": {
      "types": [
        "string"
      ],
      "required": true
    },
    "rel": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "goal_changed": {
    "goal": {
      "types": [
        "string"
      ],
      "required": true
    },
    "status": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "none",
        "active",
        "completed",
        "blocked"
      ]
    },
    "elapsed_seconds": {
      "types": [
        "integer"
      ],
      "required": false
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "info": {
    "message": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "error": {
    "message": {
      "types": [
        "string"
      ],
      "required": true
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "request_expired": {
    "id": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "permission_request": {
    "id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "call_id": {
      "types": [
        "null",
        "string"
      ],
      "required": false
    },
    "name": {
      "types": [
        "string"
      ],
      "required": true
    },
    "args": {
      "types": [
        "object"
      ],
      "required": true
    },
    "command": {
      "types": [
        "null",
        "string"
      ],
      "required": false
    },
    "suggested_rule": {
      "types": [
        "string"
      ],
      "required": true
    },
    "choices": {
      "types": [
        "array"
      ],
      "required": true
    }
  },
  "rule_added": {
    "rule": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "plan_proposal": {
    "id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "plan": {
      "types": [
        "string"
      ],
      "required": true
    },
    "choices": {
      "types": [
        "array"
      ],
      "required": true
    }
  },
  "options_request": {
    "id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "question": {
      "types": [
        "string"
      ],
      "required": true
    },
    "options": {
      "types": [
        "array"
      ],
      "required": true
    }
  },
  "mcp_input_request": {
    "id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "server": {
      "types": [
        "string"
      ],
      "required": true
    },
    "kind": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "elicitation",
        "sampling_request",
        "sampling_response"
      ]
    },
    "payload": {
      "types": [
        "object"
      ],
      "required": true
    }
  },
  "context": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    },
    "used": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "size": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "compact_threshold": {
      "types": [
        "number"
      ],
      "required": false
    },
    "compact_at": {
      "types": [
        "integer"
      ],
      "required": false
    },
    "input_tokens": {
      "types": [
        "integer"
      ],
      "required": false
    },
    "output_tokens": {
      "types": [
        "integer"
      ],
      "required": false
    },
    "cached_input_tokens": {
      "types": [
        "integer"
      ],
      "required": false
    },
    "reasoning_tokens": {
      "types": [
        "integer"
      ],
      "required": false
    },
    "requests": {
      "types": [
        "integer"
      ],
      "required": false
    }
  },
  "compacted": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    },
    "status": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "compacted",
        "pruned",
        "unchanged"
      ]
    },
    "strategy": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "provider_native",
        "model_summary",
        "mechanical",
        "tool_prune",
        "none"
      ]
    },
    "trigger": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "automatic",
        "manual",
        "overflow",
        "resume"
      ]
    },
    "before_tokens": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "after_tokens": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "context_size": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "freed_tokens": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "fallback_reason": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "artifacts": {
    "items": {
      "types": [
        "array"
      ],
      "required": true
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "config": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    },
    "model": {
      "types": [
        "string"
      ],
      "required": true
    },
    "mode": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "default",
        "acceptEdits",
        "plan",
        "auto"
      ]
    },
    "think": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "off",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "base_url": {
      "types": [
        "string"
      ],
      "required": true
    },
    "api_mode": {
      "types": [
        "string"
      ],
      "required": false
    },
    "provider_state": {
      "types": [
        "string"
      ],
      "required": false
    },
    "prompt_cache": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "capability_cache_ttl_s": {
      "types": [
        "integer"
      ],
      "required": false
    },
    "provider_capabilities": {
      "types": [
        "object"
      ],
      "required": false
    },
    "project_root": {
      "types": [
        "string"
      ],
      "required": true
    },
    "search": {
      "types": [
        "null",
        "string"
      ],
      "required": false
    },
    "subagent_model": {
      "types": [
        "string"
      ],
      "required": false
    },
    "subagent_base_url": {
      "types": [
        "string"
      ],
      "required": false
    },
    "subagent_api_mode": {
      "types": [
        "string"
      ],
      "required": false
    },
    "subagent_api_key_set": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "fallback_model": {
      "types": [
        "string"
      ],
      "required": false
    },
    "fallback_base_url": {
      "types": [
        "string"
      ],
      "required": false
    },
    "fallback_api_mode": {
      "types": [
        "string"
      ],
      "required": false
    },
    "fallback_api_key_set": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "context_size": {
      "types": [
        "integer"
      ],
      "required": false
    },
    "goal": {
      "types": [
        "object"
      ],
      "required": true
    },
    "sandbox": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "sandbox_network": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "show_reasoning": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "preserve_thinking": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "ultra_mode": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "code_action": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "suggest": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "plan_artifact": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "artifact_autostart": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "artifact_in_plan": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "tool_profile": {
      "types": [
        "string"
      ],
      "required": false
    },
    "max_parallel_tasks": {
      "types": [
        "integer"
      ],
      "required": false
    },
    "subscription_engine": {
      "types": [
        "string"
      ],
      "required": false
    },
    "subscription_engines": {
      "types": [
        "array"
      ],
      "required": false
    },
    "subscription_model": {
      "types": [
        "string"
      ],
      "required": false
    },
    "subscription_effort": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "status": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    },
    "model": {
      "types": [
        "string"
      ],
      "required": true
    },
    "mode": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "default",
        "acceptEdits",
        "plan",
        "auto"
      ]
    },
    "think": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "off",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "base_url": {
      "types": [
        "string"
      ],
      "required": true
    },
    "subscription_engine": {
      "types": [
        "string"
      ],
      "required": false
    },
    "ultra_mode": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "goal": {
      "types": [
        "object"
      ],
      "required": true
    },
    "context_used": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "context_size": {
      "types": [
        "integer"
      ],
      "required": true
    }
  },
  "model_changed": {
    "model": {
      "types": [
        "string"
      ],
      "required": true
    },
    "base_url": {
      "types": [
        "string"
      ],
      "required": true
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "mode_changed": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    },
    "mode": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "default",
        "acceptEdits",
        "plan",
        "auto"
      ]
    },
    "workspace_trusted": {
      "types": [
        "boolean"
      ],
      "required": false
    }
  },
  "think_changed": {
    "think": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "off",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "models": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "ids": {
      "types": [
        "array"
      ],
      "required": true
    },
    "base_url": {
      "types": [
        "string"
      ],
      "required": true
    },
    "api_mode": {
      "types": [
        "string"
      ],
      "required": false
    },
    "error": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "mcp_tools": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "servers": {
      "types": [
        "array"
      ],
      "required": true
    },
    "tools": {
      "types": [
        "array"
      ],
      "required": true
    },
    "total": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "offset": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "next_offset": {
      "types": [
        "null",
        "integer"
      ],
      "required": true
    },
    "error": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "mcp_call_complete": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "call_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "name": {
      "types": [
        "string"
      ],
      "required": true
    },
    "status": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "completed",
        "denied",
        "cancelled",
        "error"
      ]
    },
    "output": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "skill_catalog": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "items": {
      "types": [
        "array"
      ],
      "required": true
    },
    "total": {
      "types": [
        "integer"
      ],
      "required": true
    }
  },
  "skill_detail": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "found": {
      "types": [
        "boolean"
      ],
      "required": true
    },
    "name": {
      "types": [
        "string"
      ],
      "required": true
    },
    "description": {
      "types": [
        "string"
      ],
      "required": true
    },
    "source": {
      "types": [
        "string"
      ],
      "required": true
    },
    "markdown": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "docs_catalog": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "items": {
      "types": [
        "array"
      ],
      "required": true
    },
    "total": {
      "types": [
        "integer"
      ],
      "required": true
    }
  },
  "doc": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "found": {
      "types": [
        "boolean"
      ],
      "required": true
    },
    "id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "title": {
      "types": [
        "string"
      ],
      "required": true
    },
    "description": {
      "types": [
        "string"
      ],
      "required": true
    },
    "markdown": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "mcp_servers": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "items": {
      "types": [
        "array"
      ],
      "required": true
    },
    "total": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "error": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "permissions": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "items": {
      "types": [
        "array"
      ],
      "required": true
    },
    "total": {
      "types": [
        "integer"
      ],
      "required": true
    }
  },
  "memory": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "project": {
      "types": [
        "string"
      ],
      "required": true
    },
    "user": {
      "types": [
        "string"
      ],
      "required": true
    },
    "message": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "session_named": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    },
    "name": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "hook_catalog": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "items": {
      "types": [
        "array"
      ],
      "required": true
    },
    "total": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "invalid": {
      "types": [
        "integer"
      ],
      "required": true
    }
  },
  "hook_activity": {
    "event": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "SessionStart",
        "UserPromptSubmit",
        "PreToolUse",
        "PostToolUse",
        "PreCompact",
        "Stop"
      ]
    },
    "status": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "started",
        "completed",
        "blocked",
        "cancelled",
        "error"
      ]
    },
    "configured": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "duration_ms": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "message": {
      "types": [
        "null",
        "string"
      ],
      "required": false
    }
  },
  "handoff_started": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "handoff": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "status": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "completed",
        "cancelled",
        "error"
      ]
    },
    "markdown": {
      "types": [
        "string"
      ],
      "required": true
    },
    "path": {
      "types": [
        "null",
        "string"
      ],
      "required": false
    },
    "error": {
      "types": [
        "null",
        "string"
      ],
      "required": false
    }
  },
  "queued": {
    "count": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "text": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "command_rejected": {
    "message": {
      "types": [
        "string"
      ],
      "required": true
    },
    "command": {
      "types": [
        "string"
      ],
      "required": false
    },
    "reason": {
      "types": [
        "string"
      ],
      "required": false
    },
    "count": {
      "types": [
        "integer"
      ],
      "required": false
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "workspace_roots": {
    "roots": {
      "types": [
        "array"
      ],
      "required": true
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "saved_plan": {
    "plan": {
      "types": [
        "string"
      ],
      "required": true
    },
    "exists": {
      "types": [
        "boolean"
      ],
      "required": true
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "session": {
    "kind": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "new",
        "cleared",
        "resumed"
      ]
    },
    "message_count": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "session_id": {
      "types": [
        "string"
      ],
      "required": false
    },
    "path": {
      "types": [
        "string"
      ],
      "required": false
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "history": {
    "items": {
      "types": [
        "array"
      ],
      "required": true
    }
  },
  "sessions": {
    "items": {
      "types": [
        "array"
      ],
      "required": true
    },
    "deleted": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "checkpoints": {
    "items": {
      "types": [
        "array"
      ],
      "required": true
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "rewound": {
    "ok": {
      "types": [
        "boolean"
      ],
      "required": true
    },
    "files_restored": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "retained_tasks": {
    "items": {
      "types": [
        "array"
      ],
      "required": true
    },
    "errors": {
      "types": [
        "array"
      ],
      "required": false
    },
    "total": {
      "types": [
        "integer"
      ],
      "required": false
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  }
};
const COMMAND_FIELDS: Record<string, Record<string, FieldSpec>> = {
  "prompt": {
    "text": {
      "types": [
        "string"
      ],
      "required": true
    },
    "images": {
      "types": [
        "null",
        "array"
      ],
      "required": false
    },
    "context": {
      "types": [
        "null",
        "array"
      ],
      "required": false
    }
  },
  "slash_command": {
    "text": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "set_workspace_roots": {
    "roots": {
      "types": [
        "array"
      ],
      "required": true
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "permission_response": {
    "id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "decision": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "once",
        "always",
        "deny",
        "no"
      ]
    },
    "rule": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "plan_response": {
    "id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "decision": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "auto",
        "acceptEdits",
        "default",
        "reject"
      ]
    },
    "feedback": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "options_response": {
    "id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "choice": {
      "types": [
        "string",
        "integer"
      ],
      "required": true
    }
  },
  "mcp_input_response": {
    "id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "action": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "accept",
        "decline",
        "cancel"
      ]
    },
    "content": {
      "types": [
        "object"
      ],
      "required": false
    }
  },
  "cancel": {},
  "interrupt": {},
  "set_mode": {
    "mode": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "default",
        "acceptEdits",
        "plan",
        "auto"
      ]
    },
    "acknowledge_workspace_trust": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "set_model": {
    "model": {
      "types": [
        "string"
      ],
      "required": false
    },
    "base_url": {
      "types": [
        "string"
      ],
      "required": false
    },
    "api_key": {
      "types": [
        "string"
      ],
      "required": false
    },
    "route": {
      "types": [
        "string"
      ],
      "required": false,
      "enum": [
        "native",
        "subscription"
      ]
    },
    "clear_stored_api_key": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "list_models": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "list_mcp_tools": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "offset": {
      "types": [
        "integer"
      ],
      "required": false
    },
    "limit": {
      "types": [
        "integer"
      ],
      "required": false
    }
  },
  "call_mcp_tool": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "call_id": {
      "types": [
        "string"
      ],
      "required": false
    },
    "name": {
      "types": [
        "string"
      ],
      "required": true
    },
    "arguments": {
      "types": [
        "object"
      ],
      "required": true
    }
  },
  "list_skills": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "reload_skills": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "get_skill": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "name": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "list_docs": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "get_doc": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "id": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "list_mcp_servers": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "upsert_mcp_server": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "name": {
      "types": [
        "string"
      ],
      "required": true
    },
    "runtime": {
      "types": [
        "object"
      ],
      "required": true
    },
    "persisted": {
      "types": [
        "object"
      ],
      "required": true
    }
  },
  "remove_mcp_server": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "name": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "reload_mcp_servers": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "list_permissions": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "add_permission_rule": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "action": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "allow",
        "ask",
        "deny"
      ]
    },
    "rule": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "remove_permission_rule": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "action": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "allow",
        "ask",
        "deny"
      ]
    },
    "rule": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "get_memory": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "add_memory": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "scope": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "project",
        "user"
      ]
    },
    "text": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "list_hooks": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    }
  },
  "generate_handoff": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "save": {
      "types": [
        "boolean"
      ],
      "required": false
    }
  },
  "set_think": {
    "level": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "off",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "set_goal": {
    "text": {
      "types": [
        "string"
      ],
      "required": false
    },
    "status": {
      "types": [
        "string"
      ],
      "required": false,
      "enum": [
        "none",
        "active",
        "completed",
        "blocked"
      ]
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "get_goal": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "get_plan": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "new_session": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "name_session": {
    "name": {
      "types": [
        "string"
      ],
      "required": true
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "clear_session": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "resume_session": {
    "path": {
      "types": [
        "null",
        "string"
      ],
      "required": false
    },
    "latest": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "list_sessions": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "delete_session": {
    "path": {
      "types": [
        "string"
      ],
      "required": true
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "list_checkpoints": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "rewind": {
    "index": {
      "types": [
        "integer"
      ],
      "required": true
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "list_retained_tasks": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "resolve_retained_task": {
    "id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "action": {
      "types": [
        "string"
      ],
      "required": true,
      "enum": [
        "apply",
        "drop"
      ]
    },
    "confirm": {
      "types": [
        "boolean"
      ],
      "required": false
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "compact": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "list_artifacts": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "stop_artifact": {
    "id": {
      "types": [
        "string"
      ],
      "required": true
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "set_config": {
    "values": {
      "types": [
        "object"
      ],
      "required": true
    },
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "get_config": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "status": {
    "request_id": {
      "types": [
        "string"
      ],
      "required": false
    }
  },
  "shutdown": {}
};

function isObject(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function typeOk(value: unknown, kind: string): boolean {
  if (kind === "null") return value === null;
  if (kind === "string") return typeof value === "string";
  if (kind === "boolean") return typeof value === "boolean";
  if (kind === "integer") return Number.isSafeInteger(value);
  if (kind === "number") return typeof value === "number" && Number.isFinite(value)
    && Math.abs(value) <= Number.MAX_SAFE_INTEGER;
  if (kind === "array") return Array.isArray(value);
  if (kind === "object") return isObject(value);
  return false;
}

function shown(value: unknown): string {
  if (typeof value === "string") {
    const short = value.slice(0, 128) + (value.length > 128 ? "…" : "");
    return JSON.stringify(short);
  }
  if (value === null || ["number", "boolean", "undefined"].includes(typeof value)) {
    return String(value);
  }
  return `<${Array.isArray(value) ? "array" : typeof value}>`;
}

function messageError(value: unknown, specs: Record<string, Record<string, FieldSpec>>,
                      sequence: boolean): string | undefined {
  if (!isObject(value)) return "message must be an object";
  const name = value.type;
  if (typeof name !== "string" || !Object.prototype.hasOwnProperty.call(specs, name)) {
    return `unknown message type ${shown(name)}`;
  }
  if (sequence && (!Number.isSafeInteger(value.seq) || Number(value.seq) < 0)) {
    return "event seq must be a non-negative integer";
  }
  const allowed = new Set(["type", ...(sequence ? ["seq"] : []), ...Object.keys(specs[name])]);
  const extra = Object.keys(value).find((key) => !allowed.has(key));
  if (extra) return `${name} has undeclared field ${shown(extra)}`;
  for (const [key, field] of Object.entries(specs[name])) {
    if (!Object.prototype.hasOwnProperty.call(value, key)) {
      if (field.required) return `${name}.${key} is required`;
      continue;
    }
    if (!field.types.some((kind) => typeOk(value[key], kind))) {
      return `${name}.${key} has the wrong type`;
    }
    if (field.enum && !field.enum.includes(value[key])) {
      return `${name}.${key} has an unsupported value`;
    }
  }
  return undefined;
}

export function dgcEventError(value: unknown): string | undefined {
  return messageError(value, EVENT_FIELDS, true);
}

export function dgcCommandError(value: unknown): string | undefined {
  return messageError(value, COMMAND_FIELDS, false);
}
